common-obj-$(CONFIG_MAX7310) += max7310.o
#Fix this later
common-obj-$(CONFIG_PL061) += pl061.o
common-obj-$(CONFIG_PUV3) += puv3_gpio.o
common-obj-$(CONFIG_ZAURUS) += zaurus.o
common-obj-$(CONFIG_E500) += mpc8xxx.o
common-obj-$(CONFIG_NETDUINOP2) += netduino_gpio.o

obj-$(CONFIG_OMAP) += omap_gpio.o
